### ISSUE TITLE
TypeError: Application.registerInjection is not a function with Emberjs RC1

### ISSUE THREAD

**Issue by arasbm** [emberjs-addons/ember-touch#15]
My first time trying to use ember-touch. I tried to include it in an Emberjs 1.0rc1

```
  <script src="js/libs/jquery-1.9.1.js"></script>
  <script src="js/libs/handlebars-1.0.0-rc.3.js"></script>
  <script src="js/libs/ember-1.0.0-rc.1.js"></script>
  <script src="js/libs/ember-touch-latest.js"></script>
```

I get the following error in the console:

```
TypeError: Application.registerInjection is not a function
[Break On This Error]   
injection: function(app, stateManager, property) {
```

Am I doing something wrong or is this a regression issue?

**Comment by ppcano** [comment]
Ember-touch works currently with ember-1.0.0-pre.2, I have been busy to upgrade ember-touch to 1.0.0.-rc.1.

I'll work on it and notify to you whenever is ready.

**Comment by ppcano** [comment]
@arasbm, i have upgraded the project to ember-1.0.0-rc.1 version and updated the link to the ember-touch release build.

Let me know if you have any issues.
