### ISSUE TITLE
SC.Gesture API should support manual trigger

### ISSUE THREAD

**Issue by lukemelia** [emberjs-addons/ember-touch#7]
I'm attempting to implement a discrete tapHold event where I look for a touchStart, movement within a threshold, and no touchEnd before a given time threshold. If the time threshold passes, I want to trigger my tapHoldEnd event. Currently, the only nice mechanism to fire the event is by implementing shouldEnd, but that doesn't get called until touchEnd. There should be a mechanism to proactively trigger a discrete event.

**Comment by lukemelia** [comment]
In case it helps think this through, here is my attempt to implement tapHold on the current API. https://gist.github.com/7233de37f8aae7a47d3b

**Comment by ppcano** [comment]
[Pull Request](https://github.com/sproutcore/sproutcore-touch/pull/9)

**Comment by ppcano** [comment]
Closing it, [TouchHoldGestureRecognizer](https://github.com/emberjs-addons/sproutcore-touch/blob/master/packages/ember-touch/lib/gesture_recognizers/touch_hold.js) has been included with the last merge.

Please, reopen it or create a new one if you are still experiencing any issues.
