### ISSUE TITLE
Touch events are not passed through child elements

### ISSUE THREAD

**Issue by ralfschimmel** [emberjs-addons/ember-touch#8]
I have a collection which has a itemViewClass. The itemViewClass has a touch configuration. Childs of the itemViewClass do not pass the touch events down to it's parent. In the code sample clicking on the string which is shown in the span does not trigger a touch event in A.someItemView, clicking besides the content of the span does work (e.g. clicking on the itemViewClass).

```
{{#collection SC.CollectionView contentBinding="content" tagName="ul" itemTagName="li" itemViewClass="A.someItemView"}}
    <span>{{content.propertyA}}</span>
{{/collection}}

A.someItemView = SC.View.extend({
    mouseDown: function(evt) {
        this.tapStart(evt);
    },

    mouseUp: function(evt) {
        this.tapEnd(evt);
    },

    tapStart: function(gesture, args) {
        this.set('selected', true);
    },

    tapCancel: function(gesture) {
        this.set('selected', false);
    },

    tapEnd: function(gesture, args) {
        this.set('selected', false);
    }
});
```

**Comment by ppcano** [comment]
The following [test](https://gist.github.com/1355632) works.

May your write a fail test?

**Comment by ralfschimmel** [comment]
[Fail test](https://gist.github.com/1391158), more complicated template with a SC.View in the itemViewClass.

**Comment by ppcano** [comment]
Your tests pass in my [fork project](https://github.com/ppcano/sproutcore-touch), i think is this [commit](https://github.com/ppcano/sproutcore-touch/commit/373cc3eef701a290ae8cf4c75eb9c8ace9cabbc7) the one which fix the problem. 

Anyway, there is a open [Pull Request](https://github.com/sproutcore/sproutcore-touch/pull/9) which fix the issue.

**Comment by ralfschimmel** [comment]
Indeed your fork fixes it, vendored your fork for now.

**Comment by ppcano** [comment]
Closing it, in favor of the last merge.
